"""fixed spelling error

Revision ID: 47e8adfc1ee0
Revises: 3f3c7f4b0c36
Create Date: 2025-07-23 10:52:38.789438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e8adfc1ee0'
down_revision: Union[str, Sequence[str], None] = '3f3c7f4b0c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
