"""Added quiz tables

Revision ID: 736fcb698619
Revises: 47e8adfc1ee0
Create Date: 2025-07-24 06:39:09.759683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '736fcb698619'
down_revision: Union[str, Sequence[str], None] = '47e8adfc1ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['xp_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_quiz_questions_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['xp_quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_quiz_user_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['xp_quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['xp_quizzes.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['xp_quiz_questions_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('xp_quiz_attempts', sa.Column('quiz_id', sa.UUID(), nullable=True))
    op.add_column('xp_quiz_attempts', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('xp_quiz_attempts', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'xp_quiz_attempts', 'xp_quizzes', ['quiz_id'], ['id'])
    op.drop_column('xp_quiz_attempts', 'subject')
    op.drop_column('xp_quiz_attempts', 'created_at')
    op.drop_column('xp_quiz_attempts', 'grade')
    op.drop_column('xp_quiz_attempts', 'questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xp_quiz_attempts', sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('xp_quiz_attempts', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('xp_quiz_attempts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('xp_quiz_attempts', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'xp_quiz_attempts', type_='foreignkey')
    op.drop_column('xp_quiz_attempts', 'completed_at')
    op.drop_column('xp_quiz_attempts', 'started_at')
    op.drop_column('xp_quiz_attempts', 'quiz_id')
    op.drop_table('xp_quiz_user_answers')
    op.drop_table('xp_quiz_questions_options')
    op.drop_table('xp_quiz_questions')
    op.drop_table('xp_quizzes')
    # ### end Alembic commands ###
